# Generated by Django 5.2.6 on 2026-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
