# Generated by Django 5.2.6 on 2026-08-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_category_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_feature',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories/default.jpg', upload_to='categories/'),
        ),
    ]
