# Generated by Django 5.2.6 on 2026-08-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_brand_created_at_alter_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
